In [1]:
import sys
import math
import numpy as np
sys.setrecursionlimit(1500)

In [2]:
# convert input txt into an 140000 * 28 array
def inputDigit(img_dir="digitdata/trainingimages"):
    with open(img_dir) as digitTxt:
        image = [list(line)[0:28] for line in digitTxt]
        rows = len(image)
        
    for i in range(rows):
        for j in range(28):
            if image[i][j] == ' ':
                image[i][j] = 0
            else:
                image[i][j] = 1
    return image

In [3]:
trainingImg = inputDigit("digitdata/trainingimages")
#print(len(trainingImg))
#print(len(trainingImg[139999]))

In [4]:
def readLable(name="digitdata/traininglabels"):
    with open(name) as label:
        labels = []
        for line in label:
            labels.append(line[0])
    return labels

In [5]:
trainingLable = readLable()
#print(len(trainingLable)

In [6]:
def mmse(preds, labels):
    error_sum = 0
    for i in len(labels):
        sum += (label[i] - preds[i]) ** 2
    return sum

In [7]:
def unrollImg(img):
    image_num = int(len(img)/28)     #each img consists of 28 lines
    unrolledImg = [[] for x in range(image_num)]          # 500*784
    offset = 0
    for i in range(image_num):  # i: 0--500
        for j in range(28):   # j: 0--28  roll num in rolled img
            unrolledImg[i] += img[offset+j]
        offset +=28

    return np.array(unrolledImg)

In [63]:
# ZERO init 10 perceptrons' weights to
def init_weights():
    weights = np.zeros((10, 784))
    return weights

In [58]:
# input: both w and x are np array
def update(w, true_y, pred_y, x, alpha=1):
    w = np.add(w, np.multiply(x, alpha * (true_y - pred_y)))
    return w

In [129]:
def train(weights, trainingImg, trainingLable, epoch_num=1000, alpha=0.5):
    alpha = 1
    trained_weights = weights
    print(trained_weights.shape)
    # iterate epoch_num times
    for e in range(epoch_num):
        # iterate through every images
        for i in range(len(trainingImg)):
            # train all 10 perceptrons with every single image
            cur_image = trainingImg[i]
            for p in range(10):
                inference = np.sign(weights[p].dot(cur_image))
                if int(trainingLable[i]) == p:
                    true_y = 1
                else:
                    true_y = -1
                trained_weights[p] = update(trained_weights[p], true_y, inference, cur_image, alpha)
                if i==10 and p==5:
                    print(np.sum(trained_weights, axis = 1))
    print(trained_weights.shape)
    return trained_weights

In [138]:
#weights = init_weights()
#print(weights[0])
#t = update(weights[5], 1, -1, np_img[2], 1)
#print(t)
#print(trainingLable)

In [131]:
weights = init_weights()
epoch_num = 30
np_img = unrollImg(trainingImg)

In [132]:
trained_weights = train(weights, np_img, trainingLable, epoch_num, alpha = 0.3)

(10, 784)
[-302. -334. -240.  146.   72. -188. -148. -148. -148. -226.]
[-1265. -1215. -1152. -1201. -1430.  -330. -1034.  -929. -1170. -2053.]
[-1688. -1424. -1467. -1193. -1690.  -806. -1126.  -891. -1807. -2199.]
[-2104. -1704. -1567. -1559. -2231.  -654. -1646.  -819. -2177. -2346.]
[-2182. -1548. -1585. -1546. -2351.  -776. -1638.  -918. -2225. -2700.]
[-2295. -1614. -1537. -1784. -2664.  -731. -1970.  -957. -2515. -2968.]
[-2373. -1706. -1877. -1755. -2714.  -848. -1793.  -870. -2787. -2984.]
[-2437. -1764. -1698. -1777. -2990.  -963. -2203. -1026. -3109. -3244.]
[-2465. -1926. -1734. -1809. -3236. -1020. -2045.  -891. -3087. -3416.]
[-2687. -2142. -1891. -2053. -3163.  -914. -2436. -1039. -3428. -3706.]
[-2577. -2194. -1915. -1993. -3232. -1100. -2424. -1288. -3572. -3551.]
[-2721. -2082. -1588. -1880. -3385. -1133. -2396. -1372. -3432. -4049.]
[-2703. -2254. -1566. -2227. -3699. -1081. -2523. -1174. -3870. -3618.]
[-2860. -2338. -1849. -2047. -3700. -1099. -2601. -1310. -4034. 

In [134]:
# input is the 10 perceptrons(weights)
# output is the prediction label for input images
def inference(weights, trainingImg):
    pred = []
    for i in range(len(trainingImg)):
        # train all 10 perceptrons with every single image
        cur_image = trainingImg[i]
        inference = np.zeros(10)
        for p in range(10):
            inference[p] = math.copysign(1, dot_product(weights[p], cur_image))
        pred.append(inference.argmax())
    return pred

In [34]:
#list = [[] for x in range(500)]
#print(len(list))
#print(len(list[0]))

#a = unrollImg(trainingImg)
#print(len(a))
#print(len(a[0]))

#w = init_weights()
#print(len(w))
#print(len(w[0]))

#print(math.copysign(1, -5))

#n = np.zeros(8)
#n[0] = 10
#print(n.argmax())



In [135]:
pred_label = inference(trained_weights, np_img)


5000


In [137]:
#print(trained_weights[1])
#print(np_img[10])
print(pred_label)

[5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 0, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9, 0, 4, 5, 3, 3, 0, 7, 4, 9, 0, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0, 0, 2, 7, 1, 6, 3, 0, 2, 1, 1, 7, 0, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1, 5, 7, 1, 7, 1, 1, 6, 3, 0, 2, 9, 3, 1, 1, 0, 4, 9, 2, 0, 0, 2, 0, 2, 7, 1, 8, 6, 4, 1, 6, 3, 4, 0, 9, 1, 3, 3, 0, 5, 4, 7, 7, 4, 2, 8, 5, 8, 6, 2, 3, 4, 6, 1, 9, 9, 6, 0, 3, 7, 2, 0, 2, 9, 4, 4, 6, 4, 9, 7, 0, 9, 2, 0, 5, 1, 5, 5, 1, 2, 3, 2, 3, 5, 9, 1, 7, 6, 2, 2, 2, 0, 5, 0, 4, 4, 9, 7, 8, 0, 2, 1, 1, 0, 3, 4, 1, 0, 0, 1, 0, 0, 1, 7, 2, 7, 3, 0, 4, 6, 5, 2, 6, 4, 7, 1, 0, 9, 0, 5, 0, 7, 1, 0, 2, 0, 3, 5, 4, 6, 5, 0, 6, 3, 7, 0, 8, 0, 9, 1, 0, 0, 1, 2, 2, 0, 3, 6, 4, 7, 5, 0, 6, 0, 7, 4, 8, 5, 9, 0, 1, 1, 4, 4, 5, 6, 4, 1, 2, 0, 3, 9, 3, 9, 0, 5, 9, 6, 5, 7, 4, 1, 3, 4, 0, 4, 8, 0, 4, 0, 6, 0, 7, 6, 0, 5, 7, 5, 7, 2, 1, 1, 6, 8, 9, 4, 1, 5, 2, 2, 4, 0, 3, 9, 6, 7, 2, 0, 3, 5, 4, 3, 6, 5, 